[package]
name = "emulator"
version = "0.1.0"
authors = ["Nir H."]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"gameboy-core" = { path = "../.."}
